version: "3.9"

services:
  prometheus: 
    image: prom/prometheus:latest
    networks:
      - profana
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - "D:/projects/profana/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:rw"
      - prometheus_data:/prometheus
    # command: "--config.file=/etc/prometheus/prometheus.yml"
  
  grafana:
    image: grafana/grafana:latest
    networks:
      - profana
    container_name: grafana
    ports: 
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
  
  cAdvisor:
    image: gcr.io/cadvisor/cadvisor
    networks:
      - profana
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro 
    devices:
      - /dev/kmsg
    restart: always

  # node-exporter:
  #   image: prom/node-exporter
  #   container_name: node_exporter
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #   command: 
  #     - '--path.procfs=/host/proc' 
  #     - '--path.sysfs=/host/sys'
  #     - --collector.filesystem.ignored-mount-points
  #     - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
  #   ports:
  #     - 9100:9100

networks:
  profana:

volumes:
  grafana_data:
  prometheus_data: